### ISSUE TITLE
Error loading auth_ad class

### ISSUE THREAD

**Issue by javaprog8432** [kathmann/Auth_AD#1]
I have this loaded into my application exactly as you instructed, but I keep getting this error:

Unable to load the requested class: auth_ad

I am hoping this is a simple issue to fix.

thanks,
Michael

**Comment by kathmann** [comment]
Hi Michael,

Thanks for the feedback. Am I right in assuming that you're getting the error when you run the loader method **$this->load->library('auth_ad');** ?

Are you getting any other errors from PHP or CI? (when you enable error reporting, of course)

Mark.

**Comment by kathmann** [comment]
For a test, could you please change the line **$this->load->library('auth_ad');** to:

**$this->load->library('Auth_AD');**

**Comment by javaprog8432** [comment]
Changing the line to:
        $this->load->library('Auth_AD');
 fixed that problem.

I now have another problem, after clicking submit to login, this pops up on the screen:

```
      LDAP PHP module not found. Please ensure that the module is loaded or compiled in.
```

Any ideas?

**Comment by javaprog8432** [comment]
Nevermind.

**Comment by kathmann** [comment]
Thanks for testing, new commit updated the example class to prevent this issue in future.
